name: Self run

on:
  pull_request

jobs:
  update-migration-percent:
    name: TS migration progress
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm i
      - name: Check files by extension
        run: node ./lib/main.js
        id: check-files
      - name: Find Comment Id
        uses: peter-evans/find-comment@v2
        id: find-comment-id
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: TS Migration
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment-id.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            TS Migration
            ${{ steps.check-files.outputs.ts-percent }}%
          edit-mode: replace
